version: "3.8"
services:
    latex:
        build:
            context: $BUILD_CONTEXT
            dockerfile: $TEMPLATE_PATH/Dockerfile
            args:
                #- NAME=$NAME
                - PROJECT_PATH=$PROJECT_PATH
                - TEMPLATE_PATH=$TEMPLATE_PATH
        environment:
            - NAME=$NAME
        image: ${IMAGE}
        container_name: ${CONTAINER}
        #tty: true
        #stdin_open: true
        #command: /bin/bash
        volumes:
            - ${PWD}:/root/ans:Z
